###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Mario",
  "lastName": "Menendez",
  "telephone": 5468462,
  "email": "mario@email.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/646fc280467775f37612ea80 HTTP/1.1

###
GET http://localhost:9000/api/users/ByEmail/diego@email.com HTTP/1.1

###
DELETE http://localhost:9000/api/users/646fc280467775f37612ea80 HTTP/1.1

###
PUT http://localhost:9000/api/users/6466dd1e611dec26bd6b2e9d HTTP/1.1
Content-Type: application/json

{
  "name": "Diego",
  "lastName": "Sicajá",
  "telephone": 42860771,
  "email": "diego@email.com"
}